const actionTypes = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT",
  SET_PROFILE: "SET_PROFILE",
  REFRESH_TOKEN: "REFRESH_TOKEN",

  GET_TRACKS_SUCCESS: "GET_TRACKS_SUCCESS",
  GET_TRACKS_FAIL: "GET_TRACKS_FAIL",
  GET_TRACKS_ERROR: "GET_TRACKS_ERROR",

  GET_ARTISTS_SUCCESS: "GET_ARTISTS_SUCCESS",
  GET_ARTISTS_FAIL: "GET_ARTISTS_FAIL",
  GET_ARTISTS_ERROR: "GET_ARTISTS_ERROR",

  SET_CURRENT_SONG: "SET_CURRENT_SONG",
  TOGGLE_PLAY: "TOGGLE_PLAY",
  QUEUE: "QUEUE",
  SET_CURRENT_INDEX: "SET_CURRENT_INDEX",

  GET_LIKE_TRACK_SUCCESS: "GET_LIKE_TRACK_SUCCESS",
  GET_LIKE_TRACK_FAIL: "GET_LIKE_TRACK_FAIL",
  LIKE_TRACK: "LIKE_TRACK",
  LIKE_TRACKS_FAIL: "LIKE_TRACKS_FAIL",
  UNLIKE_TRACK: "UNLIKE_TRACK",

  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",

  GET_PLAYLIST_SUCCESS: "GET_PLAYLIST_SUCCESS",
  GET_PLAYLIST_ID_SUCCESS: "GET_PLAYLIST_ID_SUCCESS",
  GET_PLAYLIST_FAIL: "GET_PLAYLIST_FAIL",
  GET_PLAYLIST_ERROR: "GET_PLAYLIST_ERROR",
  ADD_PLAYLIST: "ADD_PLAYLIST",
  UPDATE_PLAYLIST: "UPDATE_PLAYLIST",
  DELETE_PLAYLIST: "DELETE_PLAYLIST",

  PLAYLIST_TRACKS_SUCCESS: "PLAYLIST_TRACKS_SUCCESS",
  PLAYLIST_TRACKS_FAIL: "PLAYLIST_TRACKS_FAIL",
  PLAYLIST_TRACKS_ERROR: "PLAYLIST_TRACKS_ERROR",
  

  GET_ALBUMS_SUCCESS: "GET_ALBUMS_SUCCESS",
  GET_ALBUMS_FAIL: "GET_ALBUMS_FAIL",
  GET_ALBUMS_ERROR: "GET_ALBUMS_ERROR",

  SEARCH_REQUEST: "SEARCH_REQUEST",
  SEARCH_SUCCESS: "SEARCH_SUCCESS",
  SEARCH_FAIL: "SEARCH_FAIL",
};

export default actionTypes;
