const actionTypes = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT",
  SET_PROFILE: "SET_PROFILE",
  REFRESH_TOKEN: "REFRESH_TOKEN",

  GET_TRACKS_SUCCESS: "GET_TRACKS_SUCCESS",
  GET_TRACKS_FAIL: "GET_TRACKS_FAIL",
  GET_TRACKS_ERROR: "GET_TRACKS_ERROR",

  GET_ARTISTS_SUCCESS: "GET_ARTISTS_SUCCESS",
  GET_ARTISTS_FAIL: "GET_ARTISTS_FAIL",
  GET_ARTISTS_ERROR: "GET_ARTISTS_ERROR",

  SET_CURRENT_SONG: "SET_CURRENT_SONG",
  TOGGLE_PLAY: "TOGGLE_PLAY",

  GET_PLAYLIST_SUCCESS: "GET_PLAYLIST_SUCCESS",
  GET_PLAYLIST_FAIL: "GET_PLAYLIST_FAIL",
  GET_PLAYLIST_ERROR: "GET_PLAYLIST_ERROR",

};

export default actionTypes;
